const CONSTANTS = {
  WHITE: 0,
  BLACK: 1,

  WHITE_PAWN: 1,
  WHITE_ROOK: 2,
  WHITE_KNIGHT: 3,
  WHITE_BISHOP: 4,
  WHITE_QUEEN: 5,
  WHITE_KING: 6,

  BLACK_PAWN: -1,
  BLACK_ROOK: -2,
  BLACK_KNIGHT: -3,
  BLACK_BISHOP: -4,
  BLACK_QUEEN: -5,
  BLACK_KING: -6,

  SOCKET_IO_ENDPOINT: 'http://localhost:5069',
  CONN_STATUS_CONNECTED: 0,
  CONN_STATUS_NO_CONNECTION: -1,
  CONN_STATUS_CONNECTING: 1,

  BOARD_CONTAINER_PADDING: 20,
  BOARD_PADDING: 20,
};

export default CONSTANTS;
